#!/bin/bash
# Provision script executed inside the Tart macOS VM after first boot.
# `sm vm up mac` runs this via SSH after the VM finishes booting.
#
# Mirrors infra/vms/lima/provision.sh — exact same flow:
#   1. curl|bash the canonical install URL → bundled darwin-arm64
#      binaries from GitHub releases. No Homebrew, no Node, no npm.
#   2. Write injected keys to $PREFIX/.env (where smartchats-server
#      reads them at boot).
#   3. Symlink the install into /usr/local/bin so PATH works for
#      everything (non-login ssh, scripts, etc.).
#
# Keys come from env vars inlined into the ssh command by sm vm up.

set -euo pipefail

echo "[provision] verifying install.sh result..."
if [ ! -x /opt/smartchats/bin/smartchats ]; then
    echo "[provision] /opt/smartchats/bin/smartchats missing — running install.sh now."
    curl -fsSL https://smartchats.ai/install | sudo bash -s -- --non-interactive --prefix /opt/smartchats
fi
if [ ! -e /usr/local/bin/smartchats ]; then
    sudo ln -sf /opt/smartchats/bin/smartchats /usr/local/bin/smartchats
fi

# macOS's default non-interactive ssh PATH doesn't include /usr/local/bin
# (where we symlink the binary). path_helper(8) reads /etc/paths.d/* on
# shell init for both login and non-login shells — drop a file there so
# `ssh <vm> smartchats <cmd>` works without a full path.
if [ ! -f /etc/paths.d/smartchats ]; then
    echo "[provision] adding /usr/local/bin to system PATH via /etc/paths.d/"
    echo "/usr/local/bin" | sudo tee /etc/paths.d/smartchats >/dev/null
fi

version=$(smartchats --version 2>/dev/null || echo "(unknown)")
echo "[provision] smartchats version: $version"

# Write keys to /opt/smartchats/.env — install.sh's PREFIX/.env is where
# smartchats-server reads provider keys from at boot.
echo "[provision] writing /opt/smartchats/.env"
sudo tee /opt/smartchats/.env >/dev/null <<EOF
# Generated by sm vm up — re-injected on every boot.
${OPENAI_API_KEY:+OPENAI_API_KEY=${OPENAI_API_KEY}}
${ANTHROPIC_API_KEY:+ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}}
${GOOGLE_API_KEY:+GOOGLE_API_KEY=${GOOGLE_API_KEY}}
EOF
sudo chmod 644 /opt/smartchats/.env

echo "[provision] done. shell into the VM with: sm vm into mac"
