#!/bin/bash
# Provision script executed inside the Tart macOS VM after first boot.
# `sm vm up mac` runs this via SSH after the VM finishes booting.
#
# Mirror of infra/vms/lima/provision.sh. Same responsibilities, macOS
# tooling instead of apt.

set -euo pipefail

echo "[provision] checking node + smartchats..."

# Stock Tart macOS images don't have Homebrew or Node preinstalled.
if ! command -v brew >/dev/null 2>&1; then
    echo "[provision] installing Homebrew..."
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if ! command -v node >/dev/null 2>&1 || ! node --version | grep -q "^v24"; then
    echo "[provision] installing Node 24 via brew..."
    brew install node@24
    brew link --force --overwrite node@24
fi

if ! command -v smartchats >/dev/null 2>&1; then
    echo "[provision] installing smartchats-ai..."
    npm install -g smartchats-ai
fi

version=$(smartchats --version 2>/dev/null || echo "(unknown)")
echo "[provision] smartchats version: $version"

# Keys file location matches the Linux side (/etc/smartchats) so any
# tooling that reads from there works the same.
echo "[provision] writing /etc/smartchats/keys.env"
sudo install -d -m 700 /etc/smartchats
sudo tee /etc/smartchats/keys.env >/dev/null <<EOF
# Generated by sm vm up — re-injected on every boot.
${OPENAI_API_KEY:+OPENAI_API_KEY=${OPENAI_API_KEY}}
${ANTHROPIC_API_KEY:+ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}}
${GOOGLE_API_KEY:+GOOGLE_API_KEY=${GOOGLE_API_KEY}}
EOF
sudo chmod 600 /etc/smartchats/keys.env

# zsh is the default macOS shell — write loader to /etc/zshenv so every
# new shell picks up the keys.
if ! grep -q "smartchats/keys.env" /etc/zshenv 2>/dev/null; then
    sudo tee -a /etc/zshenv >/dev/null <<'EOF'

# Auto-loaded by sm vm provisioning. Loads API keys from the host-
# injected file so smartchats launch picks them up.
if [ -r /etc/smartchats/keys.env ]; then
    set -a
    . /etc/smartchats/keys.env
    set +a
fi
EOF
fi

echo "[provision] done. shell into the VM with: sm vm into mac"
