import type { PairedDesignPack } from '../types';

/**
 * Dev Tools design pack — developer tools / IDE aesthetic with navy background,
 * green primary (run/success) and sky blue accent. IBM Plex Sans body font.
 */
export const devToolsPack: PairedDesignPack = {
  id: 'dev_tools',
  name: 'Dev Tools',
  description: 'Developer tools / IDE aesthetic with green and sky blue accents',
  dark: {
    id: 'dev_tools-dark',
    name: 'Dev Tools Dark',
    description: 'Dark IDE-inspired theme with green accents',
    mode: 'dark',
    color: {
      background: '#0f172a',
      surface: '#1b2336',
      surfaceAlt: '#272f42',
      text: '#f8fafc',
      textMuted: 'rgba(148, 163, 184, 0.8)',
      primary: '#22c55e',
      accent: '#38bdf8',
      border: 'rgba(71, 85, 105, 0.5)',
      danger: '#ef4444',
      success: '#22c55e',
      warning: '#fbbf24',
    },
    surface: {
      elevated: 'linear-gradient(to bottom, #202940 0%, #1b2336 100%)',
      insetHighlight: 'inset 0 1px 0 rgba(34, 197, 94, 0.05)',
    },
    shadow: {
      sm: '0 1px 2px rgba(0, 0, 0, 0.5)',
      md: '0 2px 8px rgba(0, 0, 0, 0.4)',
      lg: '0 8px 24px rgba(0, 0, 0, 0.5)',
      xl: '0 16px 48px rgba(0, 0, 0, 0.6)',
    },
    opacity: {
      hover: 0.06,
      pressed: 0.1,
      disabled: 0.35,
      overlay: 0.6,
    },
    typography: {
      fontSans: '"IBM Plex Sans", "Inter", sans-serif',
      fontMono: '"JetBrains Mono", "Fira Code", monospace',
      scale: 'base',
      weight: 400,
      sizes: { xs: '0.75rem', sm: '0.875rem', base: '1rem', lg: '1.125rem', xl: '1.25rem', '2xl': '1.5rem' },
      weights: { normal: 400, medium: 500, semibold: 600, bold: 700 },
      lineHeights: { tight: 1.25, normal: 1.5, relaxed: 1.75 },
    },
    space: {
      unit: 8,
      density: 'comfortable',
    },
    radius: {
      sm: 4,
      md: 6,
      lg: 10,
    },
    motion: {
      durationFast: '100ms',
      durationBase: '160ms',
      easing: 'cubic-bezier(0.25, 1, 0.5, 1)',
    },
    componentRules: {
      panelStyle: 'elevated',
      buttonStyle: 'solid',
      messageStyle: 'flat',
      inputStyle: 'outlined',
      badgeStyle: 'soft',
      tooltipStyle: 'solid',
      dividerStyle: 'solid',
      focusRingStyle: 'ring',
    },
  },
  light: {
    id: 'dev_tools-light',
    name: 'Dev Tools Light',
    description: 'Light IDE-inspired theme with green accents',
    mode: 'light',
    color: {
      background: '#f8fafc',
      surface: '#ffffff',
      surfaceAlt: '#f1f5f9',
      text: '#0f172a',
      textMuted: 'rgba(15, 23, 42, 0.55)',
      primary: '#16a34a',
      accent: '#0284c7',
      border: 'rgba(0, 0, 0, 0.1)',
      danger: '#dc2626',
      success: '#16a34a',
      warning: '#d97706',
    },
    surface: {
      elevated: 'linear-gradient(to bottom, #ffffff 0%, #f8fafc 100%)',
      insetHighlight: 'inset 0 1px 0 rgba(255, 255, 255, 0.6)',
    },
    shadow: {
      sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
      md: '0 2px 8px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)',
      lg: '0 8px 24px rgba(0, 0, 0, 0.1), 0 2px 8px rgba(0, 0, 0, 0.05)',
      xl: '0 16px 48px rgba(0, 0, 0, 0.14), 0 4px 16px rgba(0, 0, 0, 0.07)',
    },
    opacity: {
      hover: 0.04,
      pressed: 0.08,
      disabled: 0.38,
      overlay: 0.4,
    },
    typography: {
      fontSans: '"IBM Plex Sans", "Inter", sans-serif',
      fontMono: '"JetBrains Mono", "Fira Code", monospace',
      scale: 'base',
      weight: 400,
      sizes: { xs: '0.75rem', sm: '0.875rem', base: '1rem', lg: '1.125rem', xl: '1.25rem', '2xl': '1.5rem' },
      weights: { normal: 400, medium: 500, semibold: 600, bold: 700 },
      lineHeights: { tight: 1.25, normal: 1.5, relaxed: 1.75 },
    },
    space: {
      unit: 8,
      density: 'comfortable',
    },
    radius: {
      sm: 4,
      md: 6,
      lg: 10,
    },
    motion: {
      durationFast: '100ms',
      durationBase: '160ms',
      easing: 'cubic-bezier(0.25, 1, 0.5, 1)',
    },
    componentRules: {
      panelStyle: 'elevated',
      buttonStyle: 'solid',
      messageStyle: 'flat',
      inputStyle: 'outlined',
      badgeStyle: 'soft',
      tooltipStyle: 'solid',
      dividerStyle: 'solid',
      focusRingStyle: 'ring',
    },
  },
};
