#!/bin/bash
# Provision script executed inside the Lima VM after first boot.
# `sm vm up` runs this via `limactl shell <name> bash provision.sh`.
#
# Responsibilities:
#   1. Verify smartchats is installed and on PATH (cloud-init does the
#      initial `npm i -g smartchats-ai`; this is the fallback).
#   2. Install the runtime binaries `smartchats start` needs:
#        - bun     (smartchats-local-server is bun-driven)
#        - surreal (the database)
#      Both are end-user-canonical install paths (curl|sh). No Docker.
#   3. Place injected API keys at /etc/smartchats/keys.env (root-only).
#   4. Print install info.

set -euo pipefail

echo "[provision] verifying install.sh result..."
# install.sh extracted to /opt/smartchats during cloud-init. Symlink the
# binary into /usr/local/bin so PATH works for everyone (limactl shell
# starts non-login; install.sh's rc-modification path doesn't apply).
if [ ! -x /opt/smartchats/bin/smartchats ]; then
    echo "[provision] /opt/smartchats/bin/smartchats missing — install.sh failed in cloud-init."
    echo "[provision] retrying install.sh now..."
    curl -fsSL https://smartchats.ai/install | sudo bash -s -- --non-interactive --prefix /opt/smartchats
fi
if [ ! -e /usr/local/bin/smartchats ]; then
    sudo ln -sf /opt/smartchats/bin/smartchats /usr/local/bin/smartchats
fi

version=$(smartchats --version 2>/dev/null || echo "(unknown)")
echo "[provision] smartchats version: $version"

# Write keys to /opt/smartchats/.env — install.sh's PREFIX/.env is where
# smartchats-server reads provider keys from at boot (same file the
# interactive `smartchats env` walkthrough writes to). Putting them here
# means `smartchats start` picks them up without any extra wiring.
echo "[provision] writing /opt/smartchats/.env"
sudo tee /opt/smartchats/.env >/dev/null <<EOF
# Generated by sm vm up — re-injected on every boot.
${OPENAI_API_KEY:+OPENAI_API_KEY=${OPENAI_API_KEY}}
${ANTHROPIC_API_KEY:+ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}}
${GOOGLE_API_KEY:+GOOGLE_API_KEY=${GOOGLE_API_KEY}}
EOF
# 644 — VM is ephemeral single-user sandbox; keys come from host shell
# env each boot, never persisted to disk image.
sudo chmod 644 /opt/smartchats/.env

echo "[provision] done. shell into the VM with: sm vm into linux"
